document.addEventListener("DOMContentLoaded", function () {
  let root = document.getElementById("jpo-partenaires") || document.getElementById("jpopartenaires") || document.getElementById("semainejpo-partenaires");
  if (!root) { root = document.createElement("div"); root.id = "jpo-partenaires"; document.body.appendChild(root); }

  const PROPOSITIONS_CSV = "https://docs.google.com/spreadsheets/d/e/2PACX-1vRlOuGBqQd5-kgMjcd_8qx2q52HrHsBfEtNH_ZtZWgw2hQkHgOY99yIY37PxPppODZRNvIa3C9m0Jnv/pub?gid=1276704150&single=true&output=csv";
  const DEMANDES_CSV = "https://docs.google.com/spreadsheets/d/e/2PACX-1vQsA_JKLqgZg_VcrL_-g7PEp_8hVy8XudkP6EBXbiOlHNindQlK4zF8n4Ul3u1xuJu2rTOmr_ySckJN/pub?gid=2115667462&single=true&output=csv";
  const CROWD_THRESHOLD = 30;

  const DAYS = [
    { iso: "2026-06-15", label: "Lundi 15 juin", short: "Lun. 15" },
    { iso: "2026-06-16", label: "Mardi 16 juin", short: "Mar. 16" },
    { iso: "2026-06-17", label: "Mercredi 17 juin", short: "Mer. 17" },
    { iso: "2026-06-18", label: "Jeudi 18 juin", short: "Jeu. 18" },
    { iso: "2026-06-19", label: "Vendredi 19 juin", short: "Ven. 19" },
    { iso: "2026-06-20", label: "Samedi 20 juin", short: "Sam. 20" },
    { iso: "2026-06-21", label: "Dimanche 21 juin", short: "Dim. 21" }
  ];
  const AUTO_DAYS = ["2026-06-15", "2026-06-16", "2026-06-18", "2026-06-19"];
  const AUTO_SLOTS = [["09:00","10:00"],["10:00","11:00"],["11:00","12:00"],["14:00","15:00"],["15:00","16:00"],["16:00","17:00"]];
  const ROOM_ORDER = ["auditorium","orchestre","chant","choeur","theatre","danse1","danse2","danse3","eveil","other","any"];
  const ROOM_DEFAULTS = {
    auditorium:{label:"Auditorium",short:"Auditorium",capacity:165,pole:"Auditorium / présentations"},
    orchestre:{label:"Salle d'orchestre",short:"Orchestre",capacity:35,pole:"Orchestre / instruments"},
    chant:{label:"Salle de chant",short:"Chant",capacity:35,pole:"Voix / chant / chœur"},
    choeur:{label:"Salle de chœur",short:"Chœur",capacity:35,pole:"Voix / chant / chœur"},
    theatre:{label:"Salle de théâtre",short:"Théâtre",capacity:35,pole:"Théâtre"},
    danse1:{label:"Studio de danse 1",short:"Danse 1",capacity:35,pole:"Danse"},
    danse2:{label:"Studio de danse 2",short:"Danse 2",capacity:35,pole:"Danse"},
    danse3:{label:"Studio de danse 3",short:"Danse 3",capacity:35,pole:"Danse"},
    eveil:{label:"Salle d'éveil",short:"Éveil",capacity:20,pole:"Éveil / accueil"},
    other:{label:"Autre espace / salle précisée",short:"Autre",capacity:35,pole:"Autre espace"},
    any:{label:"À arbitrer",short:"À arbitrer",capacity:35,pole:"À arbitrer"}
  };

  let allSlots = [], activeDay = "all", activeMode = "all", searchTerm = "";

  root.innerHTML = `
  <style>
    #jpo-partenaires{--text:#111827;--muted:#64748b;--border:#e5e7eb;font-family:Arial,sans-serif;color:var(--text);width:100%}#jpo-partenaires *{box-sizing:border-box}
    #jpo-partenaires .wrap{max-width:1120px;margin:0 auto;background:#fff;border:1px solid var(--border);border-radius:26px;overflow:hidden;box-shadow:0 18px 50px rgba(15,23,42,.08)}
    #jpo-partenaires .head{padding:30px;background:radial-gradient(circle at top right,rgba(37,99,235,.13),transparent 34%),radial-gradient(circle at top left,rgba(22,163,74,.10),transparent 30%),#fff;border-bottom:1px solid var(--border)}
    #jpo-partenaires h2{margin:0;font-size:clamp(30px,4vw,44px);line-height:1.04;letter-spacing:-.045em}#jpo-partenaires .sub{margin:12px 0 0;color:var(--muted);font-size:16px;line-height:1.6;max-width:940px;font-weight:750}
    #jpo-partenaires .intro{margin-top:18px;border:1px solid #dbeafe;background:#eff6ff;color:#1e3a8a;border-radius:20px;padding:16px;font-size:14px;line-height:1.55;font-weight:800}#jpo-partenaires .intro strong{color:#111827;font-weight:900}
    #jpo-partenaires .content{padding:22px}.stats{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-bottom:16px}.stat{border:1px solid var(--border);border-radius:18px;padding:14px;background:#fff}.num{font-size:28px;font-weight:900;line-height:1}.lab{margin-top:5px;color:var(--muted);font-size:12px;font-weight:900;line-height:1.3}
    #jpo-partenaires .toolbar{display:grid;grid-template-columns:1.4fr 1fr 1fr;gap:10px;margin-bottom:18px;align-items:end}.tool label{display:block;font-size:12px;color:#475569;font-weight:900;margin-bottom:5px;text-transform:uppercase}select,input{width:100%;border:1px solid #cbd5e1;border-radius:14px;padding:11px;font-size:14px;font-weight:800;background:#fff}
    .focus{margin:0 0 22px;border:1px solid #fde68a;background:#fffbeb;border-radius:24px;overflow:hidden}.focus-head{padding:17px 18px;border-bottom:1px solid #fde68a;background:#fff7ed}.focus-title{font-size:22px;font-weight:900;letter-spacing:-.035em;color:#78350f;text-transform:uppercase}.focus-sub{margin-top:4px;color:#92400e;font-size:13px;font-weight:800;line-height:1.4}.focus-body{padding:14px}.days{display:grid;gap:22px}
    .day{border:1px solid var(--border);border-radius:24px;overflow:hidden;background:#fff}.dayhead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;padding:18px;background:#f8fafc;border-bottom:1px solid var(--border)}.daytitle{font-size:24px;font-weight:900;text-transform:uppercase;letter-spacing:-.035em}.daymeta{margin-top:4px;color:#64748b;font-size:13px;font-weight:850;line-height:1.4}.badge{border-radius:999px;background:#e2e8f0;color:#334155;padding:7px 10px;font-size:12px;font-weight:900;white-space:nowrap}.daybody{padding:14px}
    .moment{margin-bottom:14px;border:1px solid #e7eaee;border-radius:20px;overflow:hidden;background:#fff}.moment.strong{border-color:#fbbf24;background:linear-gradient(180deg,#fffbeb 0,#fff 45%)}.momenthead{padding:14px 15px;background:#fbfcfd;border-bottom:1px solid #edf0f3;display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.momenttime{font-size:20px;font-weight:900;letter-spacing:-.02em}.momentsub{margin-top:4px;color:#64748b;font-size:12px;font-weight:850}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:12px;padding:12px}.card{border:1px solid var(--border);border-radius:18px;background:#fff;overflow:hidden;box-shadow:0 8px 20px rgba(15,23,42,.04)}.top{padding:13px;background:#fbfcfd;border-bottom:1px solid #edf0f3}.chips{display:flex;flex-wrap:wrap;gap:6px;margin-bottom:8px}.chip{border-radius:999px;background:#f1f5f9;color:#334155;padding:5px 8px;font-size:11px;font-weight:900}.chip.gold{background:#fef3c7;color:#92400e}.chip.green{background:#dcfce7;color:#166534}.chip.blue{background:#dbeafe;color:#1e40af}.title{font-size:17px;line-height:1.22;font-weight:900;letter-spacing:-.02em}.desc{margin-top:8px;color:#475569;font-size:13px;line-height:1.42;font-weight:700}.body{padding:13px;color:#334155;font-size:13px;line-height:1.5;font-weight:800}.publics{margin-top:8px;border-top:1px dashed #e5e7eb;padding-top:8px;color:#166534}.btn{border:0;background:#111827;color:#fff;border-radius:14px;padding:10px 12px;font-size:13px;font-weight:900;cursor:pointer;margin-top:10px}.empty{border:1px dashed #cbd5e1;background:#f8fafc;color:#64748b;border-radius:18px;padding:18px;font-weight:850;line-height:1.45}.error{color:#b91c1c;font-weight:900;white-space:pre-wrap}.modal{display:none;position:fixed;inset:0;z-index:999999;background:rgba(15,23,42,.55);padding:20px;align-items:center;justify-content:center}.modal.open{display:flex}.box{width:min(860px,100%);max-height:90vh;overflow:auto;background:#fff;border-radius:26px;padding:28px;position:relative;box-shadow:0 30px 80px rgba(0,0,0,.24)}.close{position:absolute;top:10px;right:14px;border:0;background:transparent;font-size:32px;cursor:pointer;color:#111827}.modaltitle{margin:0 42px 18px 0;font-size:28px;line-height:1.15;font-weight:900;letter-spacing:-.03em}.row{display:grid;grid-template-columns:170px minmax(0,1fr);gap:12px;padding:10px 0;border-bottom:1px dashed #e5e7eb;line-height:1.45}.label{font-weight:900;color:#111827}
    @media(max-width:840px){#jpo-partenaires .toolbar,#jpo-partenaires .stats{grid-template-columns:1fr}.row{grid-template-columns:1fr;gap:4px}.head,.content{padding:18px}}
  </style>
  <div class="wrap"><header class="head"><h2>JPO 2026 - repères partenaires</h2><p class="sub">Une page de lecture institutionnelle pour repérer les meilleurs moments de venue : tous les événements à l'auditorium et les créneaux où l'affluence confirmée est significative dans le Conservatoire, y compris les publics scolaires.</p><div class="intro"><strong>Principe.</strong><br>Les repères ne sont pas construits à partir des grandes salles, mais à partir de l'affluence réelle confirmée : lorsqu'un créneau cumule plusieurs groupes validés, il remonte comme moment intéressant pour une venue partenaire ou institutionnelle. Aucune réservation depuis cette page.</div></header><main class="content"><div id="jpo-partenaires-error" class="error"></div><div class="stats" id="jpo-partenaires-stats"></div><div class="toolbar"><div class="tool"><label>Recherche</label><input id="jpo-partenaires-search" type="search" placeholder="Chercher un titre, établissement, discipline..."></div><div class="tool"><label>Jour</label><select id="jpo-partenaires-day"></select></div><div class="tool"><label>Affichage</label><select id="jpo-partenaires-mode"><option value="all">Auditorium + affluence confirmée</option><option value="crowd">Affluence confirmée uniquement</option><option value="auditorium">Auditorium uniquement</option></select></div></div><section class="focus" id="jpo-partenaires-focus"></section><div class="days" id="jpo-partenaires-output"></div></main></div><div class="modal" id="jpo-partenaires-modal"><div class="box"><button type="button" class="close" data-close-modal>&times;</button><h3 class="modaltitle" id="jpo-partenaires-modal-title"></h3><div id="jpo-partenaires-modal-body"></div></div></div>`;

  const $ = id => document.getElementById(id);
  function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));}
  function norm(v){return String(v||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").trim();}
  function slug(v){return norm(v).replace(/[^a-z0-9]+/g,"-").replace(/^-+|-+$/g,"").slice(0,60);}
  function parseNumber(v){const n=parseInt(String(v||"").replace(/[^\d]/g,""),10);return isNaN(n)?0:n;}
  function compact(t){return String(t||"").replace(":","");}
  function showTime(t){return String(t||"").replace(":","h");}
  function parseCSV(text){const s=String(text||"").replace(/\r/g,"");const rows=[];let row=[],cur="",q=false;for(let i=0;i<s.length;i++){const ch=s[i],n=s[i+1];if(ch==='"'){if(q&&n==='"'){cur+='"';i++;}else q=!q;}else if(ch===","&&!q){row.push(cur);cur="";}else if(ch==="\n"&&!q){row.push(cur);rows.push(row);row=[];cur="";}else cur+=ch;}row.push(cur);rows.push(row);return rows.filter(r=>r.some(c=>String(c||"").trim()!==""));}
  function findCol(headers,names){const hs=headers.map(norm);for(const n of names){const k=norm(n);const i=hs.findIndex(h=>h===k);if(i!==-1)return i;}for(const n of names){const k=norm(n);const i=hs.findIndex(h=>h.includes(k));if(i!==-1)return i;}return -1;}
  function parseDateFR(v){const t=String(v||"").trim();if(/^\d{4}-\d{2}-\d{2}$/.test(t))return t;if(/^\d+(\.\d+)?$/.test(t)){const serial=parseFloat(t);const d=new Date(Math.round((serial-25569)*86400*1000));if(!isNaN(d.getTime()))return d.toISOString().slice(0,10);}const p=t.split(/[\/.-]/);if(p.length!==3)return null;let y=p[2];if(y.length===2)y="20"+y;return y+"-"+p[1].padStart(2,"0")+"-"+p[0].padStart(2,"0");}
  function fmtTime(v){const t=String(v||"").trim();if(/^\d+(\.\d+)?$/.test(t)){const n=parseFloat(t);if(n>=0&&n<1){const total=Math.round(n*24*60);return String(Math.floor(total/60)).padStart(2,"0")+":"+String(total%60).padStart(2,"0");}}if(/^\d{1,2}:\d{2}/.test(t)){const p=t.split(":");return p[0].padStart(2,"0")+":"+p[1].slice(0,2);}if(/^\d{1,2}h\d{0,2}$/i.test(t)){const p=t.toLowerCase().split("h");return p[0].padStart(2,"0")+":"+(p[1]||"00").padStart(2,"0");}return t.slice(0,5);}
  function minutes(t){const p=String(t||"").split(":");if(p.length<2)return null;const h=parseInt(p[0],10),m=parseInt(p[1],10);return isNaN(h)||isNaN(m)?null:h*60+m;}
  function timeFromMin(m){return String(Math.floor(m/60)).padStart(2,"0")+":"+String(m%60).padStart(2,"0");}
  function durationToMinutes(v){const d=norm(v);let m=d.match(/(\d+)\s*min/);if(m)return parseInt(m[1],10);m=d.match(/(\d+)\s*h\s*(\d+)?/);if(m)return parseInt(m[1],10)*60+parseInt(m[2]||"0",10);if(d.includes("45"))return 45;if(d.includes("30"))return 30;if(d.includes("60"))return 60;return 60;}
  function blockedDuration(format,fallback){const f=norm(format);const explicit=f.match(/bloque\s*(\d+)\s*min/);if(explicit)return parseInt(explicit[1],10);if(f.includes("bloque 30"))return 30;if(f.includes("bloque 1h")||f.includes("bloque 1 h"))return 60;return durationToMinutes(format||fallback);}
  function statusInfo(v){const s=norm(v);if(s.includes("refuse"))return"refused";if(s.includes("accepte"))return"accepted";return"pending";}
  function roomInfo(v,precision){const s=norm(v),p=String(precision||"").trim();if(s.includes("auditorium"))return{key:"auditorium",...ROOM_DEFAULTS.auditorium};if(s.includes("orchestre"))return{key:"orchestre",...ROOM_DEFAULTS.orchestre};if(s.includes("chant")&&!s.includes("choeur")&&!s.includes("chœur"))return{key:"chant",...ROOM_DEFAULTS.chant};if(s.includes("choeur")||s.includes("chœur"))return{key:"choeur",...ROOM_DEFAULTS.choeur};if(s.includes("theatre")||s.includes("théâtre"))return{key:"theatre",...ROOM_DEFAULTS.theatre};if(s.includes("danse 1"))return{key:"danse1",...ROOM_DEFAULTS.danse1};if(s.includes("danse 2"))return{key:"danse2",...ROOM_DEFAULTS.danse2};if(s.includes("danse 3"))return{key:"danse3",...ROOM_DEFAULTS.danse3};if(s.includes("danse"))return{key:"danse1",...ROOM_DEFAULTS.danse1};if(s.includes("eveil")||s.includes("éveil"))return{key:"eveil",...ROOM_DEFAULTS.eveil};if(s.includes("arbitrer"))return{key:"any",...ROOM_DEFAULTS.any};if(s.includes("autre")||p)return{key:"other",short:p||"Autre",label:p||ROOM_DEFAULTS.other.label,capacity:35,pole:ROOM_DEFAULTS.other.pole};return{key:"other",short:v||"Autre",label:v||ROOM_DEFAULTS.other.label,capacity:35,pole:ROOM_DEFAULTS.other.pole};}
  function slotId(date,start,end,room,title,index){return[date,compact(start),compact(end),room,slug(title),index].join("|");}
  function slotPrefix(slot){return[slot.dateIso,compact(slot.start),compact(slot.end),slot.roomKey].join("|")+"|";}
  function formatDate(iso){const d=DAYS.find(x=>x.iso===iso);return d?d.label:(iso||"Date à préciser");}
  function slotsOverlap(a,b){const as=minutes(a.start),ae=minutes(a.end),bs=minutes(b.start),be=minutes(b.end);if(as===null||ae===null||bs===null||be===null)return false;return as<be&&bs<ae;}
  function compareSlots(a,b){return (a.dateIso||"").localeCompare(b.dateIso||"") || (a.start||"").localeCompare(b.start||"") || (ROOM_ORDER.indexOf(a.roomKey)-ROOM_ORDER.indexOf(b.roomKey)) || a.title.localeCompare(b.title);}

  function buildReservations(rows){const map={};if(!rows.length)return map;const headers=rows[0]||[],data=rows.slice(1);const C_IDS=findCol(headers,["IDs créneaux","IDs creneaux","IDS créneaux","IDS creneaux"]);const C_VALID=findCol(headers,["VALIDATION CRD","Validation CRD"]);const C_EST=findCol(headers,["Établissement","Etablissement","Nom de l’établissement","Nom de l'etablissement","Structure","École","Ecole","Organisme"]);data.forEach(row=>{const validation=C_VALID!==-1?norm(row[C_VALID]):"";if(validation!=="oui")return;const establishment=C_EST!==-1&&row[C_EST]?String(row[C_EST]).trim():"";const ids=C_IDS!==-1&&row[C_IDS]?row[C_IDS]:(row.find(cell=>/2026-06-\d{2}\|\d{4}\|\d{4}\|/.test(String(cell||"")))||"");String(ids).split(";").map(x=>x.trim()).filter(Boolean).forEach(line=>{const parts=line.split("|").map(x=>x.trim());if(parts.length<8)return;const id=parts.slice(0,5).join("|");const group=parts[5]||"Groupe non précisé";const students=parseNumber(parts[6]);const adults=parseNumber(parts[7]);const total=students+adults;if(!id||!total)return;if(!map[id])map[id]={confirmed:0,details:[]};map[id].confirmed+=total;map[id].details.push({group,establishment,students,adults,total,state:"confirmed"});});});return map;}
  function applyReservations(slots,reservations){return slots.map(slot=>{let reservation=reservations[slot.id];if(!reservation){reservation={confirmed:0,details:[]};const prefix=slotPrefix(slot);Object.keys(reservations).forEach(id=>{if(id.indexOf(prefix)===0){reservation.confirmed+=reservations[id].confirmed||0;(reservations[id].details||[]).forEach(d=>reservation.details.push(d));}});}return{...slot,confirmed:reservation.confirmed||0,reservationDetails:reservation.details||[]};});}

  function buildSlots(rows){const h=rows[0]||[],data=rows.slice(1),out=[];const C_NAME=findCol(h,["Nom et prénom","Nom"]),C_DISC=findCol(h,["Discipline / département","Discipline"]),C_TITLE=findCol(h,["Intitulé du projet","Intitule du projet","Projet"]),C_TYPE=findCol(h,["Type de proposition","Type"]),C_PUBLIC=findCol(h,["Public visé","Public"]),C_DATE=findCol(h,["Date souhaitée","Date"]),C_TIME=findCol(h,["Horaire de début","Horaire","Heure"]),C_DUR=findCol(h,["Durée estimée","Durée"]),C_ROOM=findCol(h,["Lieu souhaité","Lieu"]),C_TECH=findCol(h,["Besoins techniques"]),C_DESC=findCol(h,["Description courte","programmation","communication"]),C_STATUS=findCol(h,["STATUT","Statut"]),C_AUTO=findCol(h,["Programmation automatique sur plusieurs créneaux ?","Programmation automatique"]),C_ROOM_FINAL=findCol(h,["SALLE RETENUE CRD","Salle retenue CRD","Salle retenue"]),C_PREC=findCol(h,["PRÉCISION SALLE / LIEU CRD","PRECISION SALLE / LIEU CRD","Précision salle","Precision salle"]),C_CAPCRD=findCol(h,["CAPACITÉ CRD","CAPACITE CRD","Capacité CRD"]),C_FORMAT=findCol(h,["FORMAT CRD","Format CRD"]),C_POLE=findCol(h,["PÔLE CRD","POLE CRD","Pôle CRD"]);if(C_TITLE===-1)throw new Error("Colonne Intitulé du projet introuvable.");data.forEach((row,index)=>{const title=row[C_TITLE]||"Proposition sans titre",rawStatus=C_STATUS!==-1?row[C_STATUS]:"",status=statusInfo(rawStatus);if(status==="refused")return;const finalRoom=C_ROOM_FINAL!==-1?row[C_ROOM_FINAL]:"",precision=C_PREC!==-1?row[C_PREC]:"",fallbackRoom=C_ROOM!==-1?row[C_ROOM]:"",room=finalRoom?roomInfo(finalRoom,precision):roomInfo(fallbackRoom,precision),capCRD=C_CAPCRD!==-1?parseNumber(row[C_CAPCRD]):0,capacity=capCRD||room.capacity||35,format=C_FORMAT!==-1?row[C_FORMAT]:"",duration=C_DUR!==-1?row[C_DUR]:"",pole=(C_POLE!==-1&&row[C_POLE])?row[C_POLE]:room.pole,autoLabel=C_AUTO!==-1?row[C_AUTO]:"",autoMode=norm(autoLabel);const common={originalIndex:index+2,title,name:C_NAME!==-1?row[C_NAME]:"",discipline:C_DISC!==-1?row[C_DISC]:"",type:C_TYPE!==-1?row[C_TYPE]:"",publicTarget:C_PUBLIC!==-1?row[C_PUBLIC]:"",description:C_DESC!==-1?row[C_DESC]:"",tech:C_TECH!==-1?row[C_TECH]:"",duration,crdFormat:format,pole,roomKey:room.key,roomLabel:room.label,roomShort:room.short,capacity,rawStatus,status,autoLabel:autoLabel||"Non"};if(autoMode.includes("oui")){AUTO_DAYS.forEach(dateIso=>AUTO_SLOTS.forEach(pair=>out.push({...common,id:slotId(dateIso,pair[0],pair[1],room.key,title,index),dateIso,start:pair[0],end:pair[1],autoGenerated:true})));}else{const dateIso=C_DATE!==-1?parseDateFR(row[C_DATE]):null,start=C_TIME!==-1?fmtTime(row[C_TIME]):"";if(!dateIso||!start)return;const end=timeFromMin(minutes(start)+blockedDuration(format,duration));out.push({...common,id:slotId(dateIso,start,end,room.key,title,index),dateIso,start,end,autoGenerated:false});}});return out.sort(compareSlots);}

  function confirmedPeak(slot){return allSlots.filter(s=>s.dateIso===slot.dateIso && slotsOverlap(slot,s)).reduce((sum,s)=>sum+(s.confirmed||0),0);}
  function momentKey(slot){return [slot.dateIso,slot.start,slot.end].join("|");}
  function buildMoments(){const m={};allSlots.forEach(slot=>{if(!slot.dateIso||!slot.start||!slot.end)return;const k=momentKey(slot);if(!m[k])m[k]={dateIso:slot.dateIso,start:slot.start,end:slot.end,slots:[],confirmed:0,auditorium:false,search:""};m[k].slots.push(slot);});Object.values(m).forEach(mm=>{mm.confirmed=mm.slots.reduce((sum,s)=>sum+(s.confirmed||0),0);mm.auditorium=mm.slots.some(s=>s.roomKey==="auditorium");mm.search=norm(mm.slots.map(s=>[s.title,s.name,s.discipline,s.pole,s.roomLabel,s.publicTarget,s.description,(s.reservationDetails||[]).map(d=>[d.establishment,d.group].join(" ")).join(" ")].join(" ")).join(" "));});return Object.values(m).filter(mm=>mm.auditorium || mm.confirmed>=CROWD_THRESHOLD).sort((a,b)=> (a.dateIso||"").localeCompare(b.dateIso||"") || (a.start||"").localeCompare(b.start||""));}
  function filteredMoments(){const q=norm(searchTerm);return buildMoments().filter(mm=>{if(activeDay!=="all"&&mm.dateIso!==activeDay)return false;if(activeMode==="crowd"&&mm.confirmed<CROWD_THRESHOLD)return false;if(activeMode==="auditorium"&&!mm.auditorium)return false;if(q&&!mm.search.includes(q))return false;return true;});}
  function publicSummary(slot){const d=slot.reservationDetails||[];if(!d.length)return "";return '<div class="publics">Public confirmé : '+d.map(x=>esc((x.establishment?x.establishment+' — ':'')+x.group+' ('+x.total+' pers.)')).join('<br>')+'</div>';}
  function renderCard(slot){return '<article class="card"><div class="top"><div class="chips">'+(slot.roomKey==="auditorium"?'<span class="chip gold">Auditorium</span>':'')+(slot.confirmed>0?'<span class="chip green">Confirmé '+slot.confirmed+'</span>':'')+'<span class="chip blue">'+esc(slot.roomLabel)+'</span></div><div class="title">'+esc(slot.title)+'</div>'+(slot.description?'<div class="desc">'+esc(slot.description)+'</div>':'')+'</div><div class="body">'+esc(slot.type||slot.discipline||"Proposition")+'<br>'+esc(slot.name||"") + publicSummary(slot)+'<br><button type="button" class="btn" data-slot-id="'+esc(slot.id)+'">Détail</button></div></article>';}
  function renderMoment(mm){const strong=mm.confirmed>=CROWD_THRESHOLD?" strong":"";const label=mm.auditorium && mm.confirmed>=CROWD_THRESHOLD ? "Auditorium + affluence confirmée" : (mm.auditorium ? "Auditorium" : "Affluence confirmée");return '<div class="moment'+strong+'"><div class="momenthead"><div><div class="momenttime">'+esc(showTime(mm.start))+' - '+esc(showTime(mm.end))+'</div><div class="momentsub">'+esc(label)+' · '+mm.confirmed+' personne(s) confirmée(s) sur ce créneau</div></div><div class="badge">'+mm.slots.length+' proposition(s)</div></div><div class="cards">'+mm.slots.sort(compareSlots).map(renderCard).join('')+'</div></div>';}
  function renderStats(moments){const aud=moments.filter(m=>m.auditorium).length,crowd=moments.filter(m=>m.confirmed>=CROWD_THRESHOLD).length,people=moments.reduce((max,m)=>Math.max(max,m.confirmed),0);$("jpo-partenaires-stats").innerHTML=[[moments.length,"créneaux repères"],[aud,"créneaux auditorium"],[people,"pic confirmé max"]].map(s=>'<div class="stat"><div class="num">'+s[0]+'</div><div class="lab">'+esc(s[1])+'</div></div>').join("");}
  function renderFocus(moments){const top=moments.filter(m=>m.confirmed>=CROWD_THRESHOLD).sort((a,b)=>b.confirmed-a.confirmed).slice(0,4);$("jpo-partenaires-focus").innerHTML=top.length?'<div class="focus-head"><div class="focus-title">Moments d’affluence confirmée</div><div class="focus-sub">Créneaux où les réservations validées cumulées atteignent au moins '+CROWD_THRESHOLD+' personnes, indépendamment de la salle.</div></div><div class="focus-body">'+top.map(renderMoment).join('')+'</div>':"";}
  function render(){const moments=filteredMoments();renderStats(moments);renderFocus(moments);if(!moments.length){$("jpo-partenaires-output").innerHTML='<div class="empty">Aucun repère à afficher avec ces filtres.</div>';return;}const days=(activeDay==="all"?DAYS:DAYS.filter(d=>d.iso===activeDay));$("jpo-partenaires-output").innerHTML=days.map(day=>{const ms=moments.filter(m=>m.dateIso===day.iso);if(!ms.length)return"";return '<section class="day"><div class="dayhead"><div><div class="daytitle">'+esc(day.label)+'</div><div class="daymeta">Auditorium et créneaux d’affluence confirmée.</div></div><div class="badge">'+ms.length+' repère(s)</div></div><div class="daybody">'+ms.map(renderMoment).join('')+'</div></section>';}).join('')||'<div class="empty">Aucun repère à afficher avec ces filtres.</div>';}
  function renderControls(){ $("jpo-partenaires-day").innerHTML='<option value="all">Toute la semaine</option>'+DAYS.map(d=>'<option value="'+d.iso+'">'+d.label+'</option>').join(''); }
  function rowHtml(label,value){return '<div class="row"><span class="label">'+esc(label)+'</span><span>'+esc(value||"—")+'</span></div>';}
  function openSlot(id){const s=allSlots.find(x=>x.id===id);if(!s)return;$("jpo-partenaires-modal-title").textContent=s.title;$("jpo-partenaires-modal-body").innerHTML=rowHtml("Date / horaire",formatDate(s.dateIso)+" — "+showTime(s.start)+"-"+showTime(s.end))+rowHtml("Lieu",s.roomLabel)+rowHtml("Affluence confirmée du créneau",confirmedPeak(s)+" personne(s)")+rowHtml("Publics confirmés",(s.reservationDetails||[]).map(d=>(d.establishment?d.establishment+" — ":"")+d.group+" : "+d.total+" personne(s)").join("\n"))+rowHtml("Type",s.type)+rowHtml("Discipline / pôle",s.pole||s.discipline)+rowHtml("Public visé",s.publicTarget)+rowHtml("Description",s.description)+rowHtml("Intervenant(s)",s.name);$("jpo-partenaires-modal").classList.add("open");}
  function bind(){["jpo-partenaires-search","jpo-partenaires-day","jpo-partenaires-mode"].forEach(id=>$(id).addEventListener(id==="jpo-partenaires-search"?"input":"change",function(){searchTerm=$("jpo-partenaires-search").value;activeDay=$("jpo-partenaires-day").value;activeMode=$("jpo-partenaires-mode").value;render();}));document.addEventListener("click",function(e){const d=e.target.closest("[data-slot-id]");if(d&&root.contains(d))openSlot(d.getAttribute("data-slot-id"));if(e.target.closest("[data-close-modal]"))$("jpo-partenaires-modal").classList.remove("open");});$("jpo-partenaires-modal").addEventListener("click",e=>{if(e.target===$("jpo-partenaires-modal"))$("jpo-partenaires-modal").classList.remove("open");});}

  fetch(PROPOSITIONS_CSV).then(r=>{if(!r.ok)throw new Error("CSV propositions HTTP "+r.status);return r.text();}).then(propText=>{return fetch(DEMANDES_CSV).then(r=>r.ok?r.text():"").catch(()=>"").then(demText=>{allSlots=applyReservations(buildSlots(parseCSV(propText)),buildReservations(parseCSV(demText||"")));renderControls();bind();render();});}).catch(err=>{$("jpo-partenaires-error").textContent="Erreur lors du chargement des propositions : "+err.message;});
});
